### ISSUE TITLE
Hi could you help with me? Why there is 10

### ISSUE THREAD

**Issue by von216** [rohan1198/Left-Atrial-Segmentation#4]
https://github.com/rohan1198/Left-Atrial-Segmentation/blob/82d38f0c6b7c79337c6eb5a97aeb9cb7f07baaf7/lib/utils.py#L74

**Comment by von216** [comment]
Could 10 be changed?

**Comment by rohan1198** [comment]
Hi, this is not my function. I got it from here: https://github.com/bragancas
As per my understanding, 10 can be changed. When the indices are being calculated, this is used to check whether the sum of the elements in a slice is greater than 10. This indicates the presence of the atrium (0=background, 1=atrium in the mask).
So 10 can be changed, but it might not work if you increase it by a lot.
An additional padding of 30 pixels on each side is also added later, so it shouldn't be too much trouble.
Please let me know if this makes sense.

**Comment by von216** [comment]
Hi, I changed 10 to 1, but there was still an error.
            start_index = None
            stop_index = None
If locator model can't predict label of the raw data,  output[index, :, :].sum() or output[(dim_range - 1) - index, :, :].sum() should be 0. the index is None. Do you have any suggestions? Thanks.
